In [2]:
import pandas as pd
import numpy as np

dos formas de configurar dos decimales en los dataframes

In [5]:
pd.options.display.float_format = '{:,.2f}'.format

In [6]:
np.set_printoptions(precision=2)

numeros aleatorios en x1 y x2


In [7]:
np.random.rand(2,5)

array([[0.11, 0.04, 0.7 , 0.48, 0.13],
       [0.95, 0.7 , 0.41, 0.39, 0.84]])

In [9]:
x1 = np.random.rand(2,5)*100
x1

array([[47.47, 51.64, 45.95, 72.75, 43.34],
       [91.85, 84.46, 67.72, 47.29, 94.54]])

In [11]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.52, -0.72, -0.74, -0.12, -0.72],
       [-0.33, -0.98, -0.78, -0.38, -0.19]])

concatenar x1 y x2 hacia abajo


In [14]:
np.concatenate([x1,x2])

array([[47.47, 51.64, 45.95, 72.75, 43.34],
       [91.85, 84.46, 67.72, 47.29, 94.54],
       [-0.52, -0.72, -0.74, -0.12, -0.72],
       [-0.33, -0.98, -0.78, -0.38, -0.19]])

In [15]:
np.concatenate([x1,x2]).shape


(4, 5)

concatenar hacia al lado

In [17]:
np.concatenate([x1,x2], axis = 1)

array([[47.47, 51.64, 45.95, 72.75, 43.34, -0.52, -0.72, -0.74, -0.12,
        -0.72],
       [91.85, 84.46, 67.72, 47.29, 94.54, -0.33, -0.98, -0.78, -0.38,
        -0.19]])

concatenar con pandas creando indices de letras

In [23]:
s1 = pd.Series(x1[0],index= ["a","b","c","d","e"])
s1


a   47.47
b   51.64
c   45.95
d   72.75
e   43.34
dtype: float64

In [25]:
s2 = pd.Series(x2[0],index=["c","d","e","f","g"])
s2

c   -0.52
d   -0.72
e   -0.74
f   -0.12
g   -0.72
dtype: float64

In [28]:
pd.concat([s1,s2])

a   47.47
b   51.64
c   45.95
d   72.75
e   43.34
c   -0.52
d   -0.72
e   -0.74
f   -0.12
g   -0.72
dtype: float64

respetando el indice

In [27]:
pd.concat([s1,s2], axis=1)

0     1
a 47.47   NaN
b 51.64   NaN
c 45.95 -0.52
d 72.75 -0.72
e 43.34 -0.74
f   NaN -0.12
g   NaN -0.72

In [29]:
s1.reset_index(drop=True)
s1

a   47.47
b   51.64
c   45.95
d   72.75
e   43.34
dtype: float64

In [31]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)],axis=1)

0     1
0 47.47 -0.52
1 51.64 -0.72
2 45.95 -0.74
3 72.75 -0.12
4 43.34 -0.72

creando df con pandas para concatenar

In [49]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=["a","b"])
df1

a    b
0 5.68 5.82
1 5.37 4.39
2 6.77 8.55

In [43]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=["a","b"],index=[2,3,4])
df2

a     b
2 -0.53 -0.83
3 -1.00 -0.72
4 -0.05 -0.56

In [55]:
pd.concat([df1,df2])

a     b
0  5.68  5.82
1  5.37  4.39
2  6.77  8.55
2 -0.53 -0.83
3 -1.00 -0.72
4 -0.05 -0.56

In [58]:
pd.concat([df1,df2],axis=1)

a    b     a     b
0 5.68 5.82   NaN   NaN
1 5.37 4.39   NaN   NaN
2 6.77 8.55 -0.53 -0.83
3  NaN  NaN -1.00 -0.72
4  NaN  NaN -0.05 -0.56

In [59]:
pd.concat([df1,df2],axis=1,join="inner")

a    b     a     b
2 6.77 8.55 -0.53 -0.83

concatenar reseteando los indices de cada dataframe

In [63]:
pd.concat([
    df1.reset_index(drop=True),
    df2.reset_index(drop=True)
    ],axis=1)

a    b     a     b
0 5.68 5.82 -0.53 -0.83
1 5.37 4.39 -1.00 -0.72
2 6.77 8.55 -0.05 -0.56

unir con append

In [67]:
df1.append(df2)

a     b
0  5.68  5.82
1  5.37  4.39
2  6.77  8.55
2 -0.53 -0.83
3 -1.00 -0.72
4 -0.05 -0.56

trasponer df

In [69]:
df1.T

0    1    2
a 5.68 5.37 6.77
b 5.82 4.39 8.55

In [76]:
df2.T

2     3     4
a -0.53 -1.00 -0.05
b -0.83 -0.72 -0.56

In [79]:
df1.T.append(df2.T).T

a    b     a     b
0 5.68 5.82   NaN   NaN
1 5.37 4.39   NaN   NaN
2 6.77 8.55 -0.53 -0.83
3  NaN  NaN -1.00 -0.72
4  NaN  NaN -0.05 -0.56